---
version: "3"

services:
   mysqldb1:
    image: mysql:latest
    container_name: mysqldb1
    ports:
      - "8833:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./database/db1:/var/lib/mysql
   admindb1:
    image: phpmyadmin:latest
    container_name: admindb1
    links:
      - mysqldb1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb1
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always

volumes:
  database: